language: cpp
sudo: required

# cache:
#   directories:
#     - $HOME/opt

branches:
  except:
    - master

before_install:
  - APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/configure-ci.sh && . ~/.profile && popd

script:
  - Tools/scripts/build_all_travis.sh

env:
  matrix:
    - TRAVIS_BUILD_TARGET="px4-v3"